services:
  backend:
    build:
      context: ./animal-eshop-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      PORT: 3000
      SOCKET_PORT: 5000
      DATABASE_HOST: 
      DATABASE_NAME: 
      DATABASE_USER: 
      DATABASE_PASSWORD: 
      JWT_SECRET: 
      DATABASE_URI: 
      CLOUDINARY_CLOUD_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 
      MAILGUN_DOMAIN: 
      MAILGUN_API_KEY: 
      FRONTEND_URL: http://localhost:5173
      UKR_NET_PASSWORD: 
      UKR_NET_EMAIL: 
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_OAUTH_REDIRECT_URL: http://localhost:5173

  frontend:
    build:
      context: ./animal-eshop-admin
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000/api
        VITE_MEDIA_URL: http://localhost:3000
        VITE_WEBSOCKET_UTL: http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - backend
